services:
  ebank-discovery-service:
    build: ./discovery-service
    container_name: ebank-discovery-service
    ports:
      - '8761:8761'
    expose:
      - '8761'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      retries: 5
  ebank-config-service:
    build: ./config-service
    container_name: ebank-config-service
    ports:
      - '9999:9999'
    expose:
      - '9999'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9999/actuator/health" ]
      interval: 10s
      retries: 5
    environment:
      - DISCOVERY_SERVICE_URL=http://ebank-discovery-service:8761/eureka
    depends_on:
      ebank-discovery-service:
        condition: service_healthy
  customer-service:
    build: ./customer-service
    container_name: customer-service
    ports:
      - '8081:8081'
    expose:
      - '8081'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
      interval: 10s
      retries: 5
    environment:
      - DISCOVERY_SERVICE_URL=http://ebank-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://ebank-config-service:9999
    depends_on:
      ebank-config-service:
        condition: service_healthy
  account-service:
    build: ./account-service
    container_name: account-service
    ports:
      - '8082:8082'
    expose:
      - '8082'
    environment:
      - DISCOVERY_SERVICE_URL=http://ebank-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://ebank-config-service:9999
    depends_on:
      customer-service:
        condition: service_healthy
  getway-service:
    build: ./geteway-service
    container_name: geteway-service
    ports:
      - '8888:8888'
    expose:
      - '8888'
    environment:
      - DISCOVERY_SERVICE_URL=http://ebank-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://ebank-config-service:9999
    depends_on:
      ebank-config-service:
        condition: service_healthy
  front-end:
    build: ./front-end
    container_name: front-end
    ports:
      - '80:80'
    expose:
      - '80'